name: ${plugin.name}
main: ${plugin.mainClass}
version: ${version}
description: ${description}
author: ${plugin.author}
website: ${url}
api-version: ${spigot.api.version}

softdepend: [floodgate, BedrockTextureLib]