name: Deploy Javadoc

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk
      - name: Prepare generation
        run: touch empty.css && chmod +x gradlew
      - name: Create JavaDoc overview page
        uses: docker://pandoc/core:2.14.1
        with:
          entrypoint: /usr/local/bin/pandoc
          args: >-
            --standalone
            -c empty.css
            --metadata title="InventoryGUIAPI"
            --output=src/main/java/overview.html
            README.md
      - name: Generate Javadoc
        run: ./gradlew javadoc
      - name: Deploy Javadoc (release)
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
          target-folder: release
        if: ${{ github.event_name == 'release' }}
      - name: Deploy Javadoc (snapshot)
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
          target-folder: snapshot
        if: ${{ github.event_name == 'push' }}
      - name: Deploy Javadoc (legacy)
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
          target-folder: legacy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/legacy' }}